### PR TITLE
Fix the readme

### PR DESCRIPTION
**Pull request by amitmerchant1990**
Hi,

I've fixed the readme to look more consistent the way I've done it [here](https://github.com/amitmerchant1990/electron-markdownify). Please check it and let me know if we can merge the same.

Thanks!

### CODE REVIEW

**Comment by Toinane** [comment]
Hey!
Thank you for your PR, otherwise I prefer the way of keep badge at the top of the readme :/

**Comment by amitmerchant1990** [comment]
Well, according to me those badges look misplaced because they appear before your actual project. Rest is upto you. I'll close the PR if you want.

**Comment by Toinane** [comment]
yeah okey why not, but can you place it after the description? :)
Thanks!

**Comment by amitmerchant1990** [comment]
Done!

**Comment by Toinane** [comment]
thank's :) !

**Pull request merged**
